Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-063d43db0594b521b
      Tags:
      - Key: "Name"
        Value: !Join
        - " "
        - - "My Instance in"
          - !Ref AWS::Region

